V1.0
AlexanderKuranov/2022-2-VK-EDU-FS-Frontend-A-Kuranov pull request #1
Opened 2022-10-07 09:05 UTC by AlexanderKuranov

# Домашнее задание № 1

Прошу @martinkomitsky, @haseprogram или @vaganov-spb проверить его.

Что было сделано:
* Прописана логика во всех трех программах
* Прописаны тесты для программы convertBytesToHuman.js

2022-10-10 20:27 UTC, martinkomitsky commented on convertBytesToHuman.test.js
> +  // ...
...?

2022-10-10 20:27 UTC, martinkomitsky requested changes
Доделать ДЗ

2022-10-12 15:04 UTC, AlexanderKuranov commented
Файл convertBytesToHuman.test.js дополнен тестами

2022-10-13 12:03 UTC, martinkomitsky approved these changes
10

2022-10-13 12:03 UTC, merged